export interface CuratedCurrencyDefinition {
  ticker: string;
  name: string;
  aliases?: string[];
}

export interface CuratedCurrencySectionDefinition {
  title: string;
  items: CuratedCurrencyDefinition[];
}

export const CURATED_CURRENCY_SECTIONS: CuratedCurrencySectionDefinition[] = [
  {
    title: 'Popular Coins',
    items: [
      { ticker: 'btc', name: 'Bitcoin' },
      { ticker: 'btc', name: 'Bitcoin (Lightning)' },
      { ticker: 'eth', name: 'Ethereum (Mainnet)' },
      { ticker: 'ltc', name: 'Litecoin (Mainnet - not MW)' },
      { ticker: 'xmr', name: 'Monero' },
      { ticker: 'bnb', name: 'Binance Coin (BSC)' },
      { ticker: 'ada', name: 'Cardano' },
      { ticker: 'doge', name: 'Dogecoin' },
      { ticker: 'pol', name: 'Polygon (Polygon)' },
      { ticker: 'xrp', name: 'Ripple (Mainnet)' },
      { ticker: 'sol', name: 'Solana' },
      { ticker: 'trx', name: 'TRON' },
    ],
  },
  {
    title: 'Stablecoins',
    items: [
      { ticker: 'busd', name: 'Binance USD (BSC)' },
      { ticker: 'busd', name: 'Binance USD (ERC20)' },
      { ticker: 'busd', name: 'Binance USD (MATIC)' },
      { ticker: 'dai', name: 'Dai (Arbitrum One)' },
      { ticker: 'dai', name: 'DAI (Base)' },
      { ticker: 'dai', name: 'Dai (BSC)' },
      { ticker: 'dai', name: 'Dai (ERC20)' },
      { ticker: 'dai', name: 'Dai (Polygon)' },
      { ticker: 'deuro', name: 'dEURO (ERC20)' },
      { ticker: 'eurc', name: 'Euro Coin (ERC20)' },
      { ticker: 'fusd', name: 'Freedom Dollar (Zano)' },
      { ticker: 'gusd', name: 'Gemini USD (ERC20)' },
      { ticker: 'usdp', name: 'Pax Dollar (ERC20)' },
      { ticker: 'usdt', name: 'Tether (ALGO)' },
      { ticker: 'usdt', name: 'Tether (Avax-c)' },
      { ticker: 'usdt', name: 'Tether (BSC)' },
      { ticker: 'usdt', name: 'Tether (EOS)' },
      { ticker: 'usdt', name: 'Tether (ERC20)' },
      { ticker: 'usdt', name: 'Tether (KAVA)' },
      { ticker: 'usdt', name: 'Tether (NEAR)' },
      { ticker: 'usdt', name: 'Tether (OMNI)' },
      { ticker: 'usdt', name: 'Tether (Polygon)' },
      { ticker: 'usdt', name: 'Tether (SOL)' },
      { ticker: 'usdt', name: 'Tether (Toncoin)' },
      { ticker: 'usdt', name: 'Tether (TRC20)' },
      { ticker: 'tusd', name: 'TrueUSD (AVAXC)' },
      { ticker: 'tusd', name: 'TrueUSD (BEP20)' },
      { ticker: 'tusd', name: 'TrueUSD (ERC20)' },
      { ticker: 'tusd', name: 'TrueUSD (Polygon)' },
      { ticker: 'tusd', name: 'TrueUSD (TRC20)' },
      { ticker: 'usdc', name: 'USDC (ALGO)' },
      { ticker: 'usdc', name: 'USDC (AVAXC)' },
      { ticker: 'usdc', name: 'USDC (Base)' },
      { ticker: 'usdc', name: 'USDC (BSC)' },
      { ticker: 'usdce', name: 'USDC.e (Optimism)' },
      { ticker: 'usdce', name: 'USDC.e (Polygon)' },
      { ticker: 'usdc', name: 'USDC (ERC20)' },
      { ticker: 'usdc', name: 'USDC (Optimism)' },
      { ticker: 'usdc', name: 'USDC (Polygon)' },
      { ticker: 'usdc', name: 'USDC (SOL)' },
      { ticker: 'usdc', name: 'USDC (TRC20)' },
    ],
  },
  {
    title: 'Other Coins',
    items: [
      { ticker: '1inch', name: '1inch (ERC20)' },
      { ticker: 'aave', name: 'Aave (ERC20)' },
      { ticker: 'algo', name: 'Algorand' },
      { ticker: 'apt', name: 'Aptos' },
      { ticker: 'arb', name: 'Arbitrum (Mainnet)' },
      { ticker: 'avax', name: 'Avalanche (C-Chain)' },
      { ticker: 'avax', name: 'Avalanche (X-Chain)' },
      { ticker: 'band', name: 'Band (ERC20)' },
      { ticker: 'bat', name: 'BAT (ERC20)' },
      { ticker: 'bdx', name: 'Beldex' },
      { ticker: 'bnb', name: 'Binance Coin (BEP2)' },
      { ticker: 'btc', name: 'Bitcoin (BEP20)' },
      { ticker: 'bch', name: 'Bitcoin Cash' },
      { ticker: 'bttc', name: 'BitTorrent-New (TRC20)' },
      { ticker: 'link', name: 'Chainlink (ERC20)' },
      { ticker: 'chz', name: 'Chiliz (ERC20)' },
      { ticker: 'atom', name: 'Cosmos (BSC)' },
      { ticker: 'atom', name: 'Cosmos (Mainnet)' },
      { ticker: 'cro', name: 'Crypto-com (ERC20)' },
      { ticker: 'crv', name: 'Curve DAO (ERC20)' },
      { ticker: 'dash', name: 'Dash' },
      { ticker: 'dcr', name: 'Decred' },
      { ticker: 'dogs', name: 'DOGS (Toncoin)' },
      { ticker: 'eos', name: 'EOS (Mainnet)' },
      { ticker: 'ergo', name: 'Ergo' },
      { ticker: 'eth', name: 'Ethereum (Arbitrum One)' },
      { ticker: 'eth', name: 'Ethereum (Base)' },
      { ticker: 'eth', name: 'Ethereum (BSC)' },
      { ticker: 'etc', name: 'Ethereum Classic' },
      { ticker: 'ftm', name: 'Fantom (ERC20)' },
      { ticker: 'fil', name: 'Filecoin (BSC)' },
      { ticker: 'fil', name: 'Filecoin (Mainnet)' },
      { ticker: 'firo', name: 'Firo (BSC)' },
      { ticker: 'firo', name: 'Firo (Mainnet - No Spark)' },
      { ticker: 'flux', name: 'Flux (BSC)' },
      { ticker: 'ftt', name: 'FTX Token (ERC20)' },
      { ticker: 'hbar', name: 'Hedera' },
      { ticker: 'hot', name: 'Holo (ERC20)' },
      { ticker: 'icp', name: 'Internet Computer' },
      { ticker: 'kava', name: 'Kava' },
      { ticker: 'kmd', name: 'Komodo' },
      { ticker: 'ldo', name: 'Lido DAO' },
      { ticker: 'ltc', name: 'Litecoin (BSC)' },
      { ticker: 'lrc', name: 'Loopring' },
      { ticker: 'mkr', name: 'Maker' },
      { ticker: 'matic', name: 'MATIC (ERC20 - Old)' },
      { ticker: 'egld', name: 'MultiversX (Mainnet)', aliases: ['MultiversX (Mainnet)', 'MultiversX'] },
      { ticker: 'xno', name: 'Nano' },
      { ticker: 'near', name: 'Near' },
      { ticker: 'near', name: 'Near (BSC)' },
      { ticker: 'xem', name: 'NEM' },
      { ticker: 'neo', name: 'Neo (N2)' },
      { ticker: 'neo', name: 'Neo (N3)' },
      { ticker: 'nexo', name: 'Nexo (ERC20)' },
      { ticker: 'okb', name: 'OKB (ERC20)' },
      { ticker: 'oxt', name: 'Orchid (ERC20)' },
      { ticker: 'cake', name: 'PancakeSwap (BSC)' },
      { ticker: 'paxg', name: 'PAX Gold (ERC20)' },
      { ticker: 'arrr', name: 'Pirate Chain' },
      { ticker: 'pivx', name: 'PIVX (No Shield)' },
      { ticker: 'dot', name: 'Polkadot (BSC)' },
      { ticker: 'dot', name: 'Polkadot (Mainnet)' },
      { ticker: 'qnt', name: 'Quant' },
      { ticker: 'rvn', name: 'Ravencoin' },
      { ticker: 'scrt', name: 'Secret (Mainnet)' },
      { ticker: 'shib', name: 'Shiba Inu (BSC)' },
      { ticker: 'shib', name: 'Shiba Inu (ERC20)' },
      { ticker: 's', name: 'Sonic (Mainnet, ex FTM)' },
      { ticker: 'xlm', name: 'Stellar (Mainnet)' },
      { ticker: 'strax', name: 'Stratis' },
      { ticker: 'sushi', name: 'SushiSwap (ERC20)' },
      { ticker: 'xtz', name: 'Tezos' },
      { ticker: 'rune', name: 'THORChain' },
      { ticker: 'ton', name: 'Toncoin (Mainnet)' },
      { ticker: 'uni', name: 'Uniswap (ERC20)' },
      { ticker: 'leo', name: 'Unus Sed Leo' },
      { ticker: 'vet', name: 'VeChain' },
      { ticker: 'waves', name: 'Waves' },
      { ticker: 'wbtc', name: 'Wrapped BTC (ERC20)', aliases: ['Wrapped Bitcoin (ERC20)'] },
      { ticker: 'weth', name: 'Wrappped ETH (Base)' },
      { ticker: 'weth', name: 'Wrappped ETH (ERC20)' },
      { ticker: 'zano', name: 'Zano' },
      { ticker: 'zec', name: 'Zcash (No UA)' },
      { ticker: 'zec', name: 'Zcash (Shielded)' },
      { ticker: 'zil', name: 'Zilliqa' },
    ],
  },
];
